### ISSUE TITLE
Question on using the docker container?

### ISSUE THREAD

**Issue by killmasta93** [vitormarcal/chatvault#97]
Hi
So i was wondering if someone could she some light, So created the docker container and the web interface shows two options
I assume one is manual and the other is the info i put in the import folder in the docker container,
The question is what do i export on whatsapp to put in the import folder? 

Thanks

**Comment by vitormarcal** [comment]
Hi!
There is a WhatsApp feature to export chats. You can find more information here: [whatsapp doc](https://faq.whatsapp.com/1180414079177245/?cms_platform=android.) By doing this, you can send it via email (which I don't recommend if the export is very large) or save it on your device. What I usually do is export directly to my server through a shared folder on my server

**Comment by killmasta93** [comment]
hi @vitormarcal Thanks for the reply, i was trying for a few days on this, but cant seem to get it working, what im trying to do is export all the convo i was looking in the android device the files but it seems to be encrypted, or do i need to export each convo? the link of the doc it seems that its not working as im getting error to many redirects 

![image](https://github.com/vitormarcal/chatvault/assets/13953629/ce1f1693-e198-45b2-b67f-e3befc2743d8)

**Comment by vitormarcal** [comment]
Sorry, the dot at the end of the url is wrong. I have corrected my previous comment with the correct link.
Anyway, the documentation says to export your chat history from a chat:

    Open the chat.
    Tap More options> More > Export chat.
    Tap Without media or Include media.

     An email will be created with your chat history attached as a .txt document.
     Note:

    If you choose Include media, the most recent media sent will be added as attachments to the email.
    When exporting with media, you can send up to 10,000 latest messages. Without media, you can send 40,000 messages. These constraints are due to maximum email sizes.

**Comment by 1291945816** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
SnailSjw, @tqft, @parzulpan, @dnha123, @zilaijuan, @DevonJerothe, @GonZo, @DevenLu, @orenyomtov, @lc7457, @atlas-comstock, @xxftapv, @rrpauls, @alex-giusi-tiri, @faraweb, @ssh-keyz, @tendant, @KnowledgeShouldBeFreeForEveryOne, @snowolf9929, @ptahdunbar
